### ISSUE TITLE
用户信息页展开含[img]标签的签名档时crash

### ISSUE THREAD

**Issue by CoolSpring8** [ttcqaq/cc98-mirror#3]
复现方式是在签名档中加入`[img][/img]`，返回个人中心展开签名档会报错`TypeError: Cannot read properties of undefined (reading 'nextId')`

本地跑了项目发现报错信息来源于[react-photo-view](https://github.com/MinJieLiu/react-photo-view)，因为`[img]`标签解析后的`PhotoView`所需的`PhotoProvider`只在[PostItem/Content.tsx](https://github.com/antct/cc98-mirror/blob/f4ac3e6b2736ff76de3ec87ea9d8532f05a40cd4/cc98-pwa/src/pages/Topic/PostItem/Content.tsx)有引入，在签名档处并没有

**Comment by antct** [comment]
应该修复了~

**Comment by CoolSpring8** [comment]
谢谢~
