### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by zdyj3170101136** [ttcqaq/cc98-mirror#4]
cc98.ttxixi.cc

**Comment by antct** [comment]
98.ttxixi.cc

**Comment by zdyj3170101136** [comment]
> 98.ttxixi.cc

what is the username?

以前我登录 cc98 的用户名都用不了

**Comment by antct** [comment]
ctrl + f5 重新刷新一下，应该就行了。之前加了一个网页验证，现在去掉了。
这个不打算长期维护了，可以用98小程序。
